name: Build Vue

on:
  push:
    branches:
      - main

env:
  GITHUB_NAME: syy11cn
  GITHUB_REPO: zeqitech.github.io
  GITHUB_EMAIL: syy11cn@outlook.com

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: $GITHUB_NAME
          reponame: $GITHUB_REPO
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
